version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      # Install dependencies into the current directory
      - pip install -r requirements.txt -t .
  build:
    commands:
      - cd . # Make sure we are in the root directory.
      - zip -r deployment-package.zip . -x "*__pycache__*" # Create a ZIP file that will be your Lambda deployment package.
      - ls -alR # For debugging (check CodeBuild logs)
artifacts:
  files:
    - deployment-package.zip
  discard-paths: yes
  base-directory: .
