version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      # Install dependencies into the current directory
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Building deployment package..." # Output a message to the console.
      - zip -r deployment-package.zip . -x "*__pycache__*" # Create a ZIP file that will be your Lambda deployment package.
      - ls # List the files in the current directory.
artifacts:
  files:
    - deployment-package.zip
  discard-paths: yes
  base-directory: .
